name: Build Yandex Cloud auth provider

on:
  push:
    branches:
      - master
      - develop
  pull_request:
      type: [opened, reopened, edited, synchronize]

jobs:
  build:
    name: Build YC Auth proivder
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '11', '17']

    env:
        MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Extract Auth API version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=ydb.auth-api.version -q -DforceStdout)
          echo "AUTH_API_VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Check Auth API version
        run: |
          echo "NEED_SDK=${{ endsWith(env.AUTH_API_VERSION, 'SNAPSHOT') }}" >> "$GITHUB_ENV"

      - name: Checkout YDB Java SDK
        if: ${{ env.NEED_SDK }}
        uses: actions/checkout@v4
        with:
          repository: ydb-platform/ydb-java-sdk
          ref: develop
          path: ydb-java-sdk

      - name: Build Auth API module
        working-directory: ./ydb-java-sdk/auth-api
        if: ${{ env.NEED_SDK }}
        run: mvn $MAVEN_ARGS install

      - name: Remove YDB Java SDK
        if: ${{ env.NEED_SDK }}
        run: rm -rf ydb-java-sdk

      - name: Download dependencies
        run: mvn $MAVEN_ARGS dependency:go-offline

      - name: Build with Maven
        run: mvn $MAVEN_ARGS package

